name: 氣象資料爬蟲

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 執行 (台灣時間早上 8:00)
  workflow_dispatch:  # 允許手動觸發 workflow

jobs:
  run-spyder:
    runs-on: ubuntu-latest

    steps:
      - name: 簽出程式碼
        uses: actions/checkout@v3

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 請根據你的程式碼實際使用的 Python 版本修改

      - name: 安裝相依套件
        run: pip install -r requirements.txt  # 建議使用 requirements.txt

      - name: 執行靜態爬蟲程式
        run: python static.py

      - name: 執行 API 爬蟲程式
        run: python api.py

      - name: 上傳結果為 artifact
        uses: actions/upload-artifact@v3
        with:
          name: crawler-output
          path: .

      # (選擇性) 如果你需要將結果 commit 回你的倉庫 (請小心使用)
      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "自動更新爬蟲結果"
      #     file_pattern: "*.csv, *.json"
